import ValueBars from '@/components/ValueBars'

function Flow({ title, steps, note }: { title: string; steps: { title: string; detail: string }[]; note: string }) {
  return <figure className="my-8 rounded-xl border border-rule bg-[color:var(--green-soft)] p-5 sm:p-6" aria-label={title}>
    <figcaption className="font-serif-display text-2xl leading-snug">{title}</figcaption>
    <ol className="mt-5 grid gap-3 sm:grid-cols-3">{steps.map((step, index) => <li key={step.title} className="rounded-lg border border-rule bg-white p-4"><span aria-hidden="true" className="mb-3 inline-flex h-8 w-8 items-center justify-center rounded-full bg-[color:var(--green)] text-sm font-semibold text-white">{index + 1}</span><strong className="block text-sm">{step.title}</strong><p className="mt-2 text-sm leading-relaxed text-[color:var(--ink-2)]">{step.detail}</p></li>)}</ol>
    <p className="mt-4 text-sm leading-relaxed text-[color:var(--ink-2)]">{note}</p>
  </figure>
}

export default function GuideVisual({ slug }: { slug: string }) {
  if (slug === 'uk-cashback-current-accounts') return <ValueBars title="A bonus changes year one, not every year" description="Illustration from this guide: £1,500 monthly eligible spending, 1% cashback capped at £10 per month, twelve qualifying months and a £2 monthly fee. A qualifying £100 bonus is added only in year one." items={[{ label: 'Cashback before fees', value: 120, tone: 'gold' }, { label: 'Recurring annual value after fees', value: 96 }, { label: 'First year including bonus', value: 196 }]}/>
  if (slug === 'uk-cashback-credit-cards-explained') return <ValueBars title="Compare what you keep after the fee" description="Illustration: £12,000 annual eligible spending, no caps or interest. Card A earns 0.5% with no annual fee; Card B earns 1% with a £30 annual fee. These are examples, not live offers." items={[{ label: 'Card A: net annual reward', value: 60 }, { label: 'Card B: net annual reward', value: 90, tone: 'gold' }]}/>
  if (slug === 'what-is-the-trading-allowance-and-how-does-it-work') return <ValueBars title="Compare deductions before calculating tax" description="Illustration: £4,500 eligible gross receipts and £400 allowable expenses. Compare the taxable profit under each method; these bars do not show the tax bill. Eligibility and other adjustments still matter." items={[{ label: 'Profit using actual expenses', value: 4100, tone: 'gold' }, { label: 'Profit using the £1,000 allowance', value: 3500 }]}/>
  if (slug === 'how-to-open-a-bank-account-as-a-new-arrival-to-the-uk' || slug === 'what-documents-do-i-need-to-open-a-uk-bank-account') return <Flow title="Your route from preparation to application" steps={[{ title: 'Check the account', detail: 'Read the specific age, residence, fees and application-channel requirements.' }, { title: 'Match your documents', detail: 'Confirm which identity and address evidence this provider accepts.' }, { title: 'Apply and follow up', detail: 'Use the official channel and respond to requests for further information.' }]} note="Provider requirements differ. Having a listed document does not guarantee approval. The guide links to the relevant instructions."/>
  if (slug === 'what-credit-cards-can-i-get-with-no-uk-credit-history') return <Flow title="Check suitability before making an application" steps={[{ title: 'Review the criteria', detail: 'Compare residence, income and address-history requirements.' }, { title: 'Check eligibility', detail: 'Use a checker that explicitly says it uses a soft search.' }, { title: 'Decide whether to apply', detail: 'Review costs and repayments; an eligibility result is not an offer.' }]} note="You do not need to borrow simply to receive wages or pay bills. Repeated applications are not a substitute for checking eligibility."/>
  if (slug === 'can-i-pay-into-my-isa-from-a-foreign-bank-account') return <Flow title="Three checks before funding an ISA" steps={[{ title: 'Subscription eligibility', detail: 'Check residence and the rules for the ISA type you want.' }, { title: 'Accepted payment route', detail: 'Ask the provider about currency, sender and nominated-account requirements.' }, { title: 'Available allowance', detail: 'Add up new subscriptions across your adult ISAs before paying in.' }]} note="A UK bank account alone does not establish ISA eligibility. Foreign savings, new subscriptions and existing ISA transfers are different things."/>
  if (slug === 'transferring-isa-uk') return <Flow title="Keep the money inside the ISA transfer process" steps={[{ title: 'Choose the receiving ISA', detail: 'Check acceptance, transfer type and any exit charges.' }, { title: 'Use its transfer form', detail: 'Let the providers arrange the move rather than withdrawing it yourself.' }, { title: 'Reconcile the records', detail: 'Check the transferred amount, interest and subscription information.' }]} note="Illustration of the process, not a timing guarantee. Lifetime ISAs and other special cases have additional rules explained in the guide."/>
  if (slug === 'can-i-claim-my-uk-pension-if-i-move-to-india') return <Flow title="Three separate pension questions" steps={[{ title: 'Your entitlement', detail: 'Obtain your own forecast or scheme benefit statement.' }, { title: 'Your payments', detail: 'Check residence notification, banking arrangements and currency costs.' }, { title: 'Your tax or transfer', detail: 'Review treaty treatment and any proposed scheme transfer separately.' }]} note="These are distinct checks, not a recommendation to transfer. Receiving pension payments abroad does not require moving the pension pot."/>
  if (slug === 'nsi-products-overview-uk') return <Flow title="Compare the type of return first" steps={[{ title: 'Prize-based saving', detail: 'Premium Bonds provide chances of prizes, not ordinary interest.' }, { title: 'Interest-paying saving', detail: 'Compare the product’s rate, access and payment arrangements.' }, { title: 'Tax-wrapped saving', detail: 'Check ISA eligibility and subscription rules as well as the return.' }]} note="This is a product-purpose map, not a ranking or rate forecast. Use the official product links in the guide for current terms."/>
  return null
}
