export const TOOL_READING: Record<string, { guides: string[]; source: string; note: string }> = {
  'net-cashback-calculator': { guides: ['uk-cashback-current-accounts', 'uk-cashback-credit-cards-explained', 'uk-cashback-explained', 'are-cashback-rewards-taxable-uk'], source: 'https://www.moneyhelper.org.uk/en/blog/everyday-money/four-ways-to-get-cashback', note: 'Uses your entered offer terms; no live product rates or approval predictions. Assumes constant monthly eligible spending and a single flat rate. Other costs must be entered separately.' },
  'take-home-pay-calculator': { guides: ['100k-tax-trap-uk', 'uk-tax-codes-explained', 'how-to-open-a-bank-account-as-a-new-arrival-to-the-uk'], source: 'https://www.gov.uk/income-tax-rates', note: 'Annual standard-allowance estimate. Actual payroll depends on your tax code, pay pattern and reliefs.' },
  'salary-sacrifice-calculator': { guides: ['100k-tax-trap-uk', 'sipp-vs-workplace-pension'], source: 'https://www.gov.uk/guidance/salary-sacrifice-and-the-effects-on-paye', note: 'Compares annual salary before and after pension salary sacrifice. Employer rules and minimum-wage restrictions still apply.' },
  'student-loan-calculator': { guides: ['student-loan-repayment-thresholds-uk', 'uk-tax-codes-explained', 'what-changed-this-tax-year'], source: 'https://www.gov.uk/repaying-your-student-loan/what-you-pay', note: 'Uses 2026/27 thresholds. Annual estimates can differ from pay-period deductions; interest and loan write-off are not modelled.' },
  'isa-allowance-tracker': { guides: ['how-many-isas-can-i-have-at-once', 'transferring-isa-uk', 'can-i-pay-into-my-isa-from-a-foreign-bank-account'], source: 'https://www.gov.uk/individual-savings-accounts', note: 'Enter new subscriptions for 6 April 2026 to 5 April 2027, not total balances or provider-to-provider transfers. It does not connect to bank records.' },
  'stamp-duty-calculator': { guides: ['first-time-buyer-route-map-uk', 'what-fees-do-i-pay-when-buying-a-house-uk'], source: 'https://www.gov.uk/stamp-duty-land-tax', note: 'Choose the property jurisdiction and applicable buyer status. Confirm reliefs, surcharges and transaction-specific treatment with your conveyancer.' },
  'mortgage-affordability-calculator': { guides: ['how-much-can-i-borrow-on-my-salary-uk', 'can-i-get-a-mortgage-on-a-visa-in-the-uk'], source: 'https://www.moneyhelper.org.uk/en/homes/buying-a-home/how-much-can-you-afford-to-borrow-for-a-mortgage', note: 'A planning range, not a mortgage offer. Lenders use their own eligibility, credit, expenditure and affordability policies.' },
  'self-assessment-tax-estimator': { guides: ['what-is-the-trading-allowance-and-how-does-it-work', 'do-i-pay-tax-on-freelance-income-alongside-a-full-time-job'], source: 'https://www.gov.uk/self-assessment-tax-returns', note: '2026/27 planning estimate for England, Wales and Northern Ireland, not the 2025/26 return due in January 2027. Excludes payments on account, student loans, loss relief, pensions and special NI interactions.' },
  'capital-gains-dividend-tax-calculator': { guides: ['cgt-shares-crypto-uk', 'dividend-tax-rate-rise-april-2026'], source: 'https://www.gov.uk/tax-on-dividends', note: 'Models standard individual allowances and rates. Special disposals, reliefs, losses and changes to tax on other income require separate assessment.' },
  'savings-tax-calculator': { guides: ['do-i-pay-tax-on-savings-interest-uk', 'cash-isa-vs-personal-savings-allowance', 'nsi-products-overview-uk'], source: 'https://www.gov.uk/apply-tax-free-interest-on-savings', note: 'Uses other income to allocate the personal allowance, starting rate and savings allowance. This result is the tax on interest only.' },
  'pension-contribution-tracker': { guides: ['what-is-the-annual-allowance-for-pension-contributions', 'sipp-vs-workplace-pension'], source: 'https://www.gov.uk/tax-on-your-private-pension/pension-tax-relief', note: 'A projection, not a guaranteed return. Check earnings-based tax-relief limits, annual allowance, threshold/adjusted income, carry-forward and MPAA separately.' },
  'emergency-fund-calculator': { guides: ['how-to-build-an-emergency-fund-uk', 'budgeting-irregular-income-uk'], source: 'https://www.moneyhelper.org.uk/en/savings/types-of-savings/emergency-savings-how-much-is-enough', note: 'A target based on the expenses and months you choose; future costs and personal risks vary.' },
}
